### ISSUE TITLE
Provision error

### ISSUE THREAD

**Issue by vodrazka** [semberal/vertica-vagrant#4]
When i do vagrant up i get:

==> default: TASK: [vertica | Install Vertica dependencies] *******************************\* 
==> default: failed: [localhost] => (item=sysstat,pstack,ntp) => {"failed": true, "item": "sysstat,pstack,ntp"}
==> default: stderr: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/n/ntp/ntp_4.2.6.p5+dfsg-3ubuntu2.14.04.3_amd64.deb  404  Not Found [IP: 91.189.92.200 80]
==> default: 
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by vodrazka** [comment]
when i ssh into and do 

apt-get update --fix-missing

its working but then i get:

TASK: [vertica | Install Vertica DEB package] ********************************\* 
failed: [localhost] => {"changed": true, "cmd": ["dpkg", "-i", "/tmp/vertica.deb"], "delta": "0:00:23.463876", "end": "2015-11-27 16:01:38.427274", "item": "", "rc": 1, "start": "2015-11-27 16:01:14.963398"}
stderr: dpkg: dependency problems prevent configuration of vertica:
 vertica depends on dialog; however:
  Package dialog is not installed.

dpkg: error processing package vertica (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 vertica
stdout: Selecting previously unselected package vertica.
(Reading database ... 61514 files and directories currently installed.)
Preparing to unpack /tmp/vertica.deb ...
Unpacking vertica (7.2.0-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...

FATAL: all hosts have already failed -- aborting

**Comment by semberal** [comment]
Hi, sorry for not responding earlier, I didn't get the notification. 
I see you are trying to install Vertica 7.2.x, which was not supported. The installation procedure has changed since 7.1.x a bit and it complains `dialog` is not installed, among other things.
However, I've just pushed support for Vertica 7.2.x, so please try it now and let me know if it works.

**Comment by vodrazka** [comment]
cool, thanks.
Doing `vagrant up` on a fresh setup gives me the same error as before. 
**BUT**
after doing `sudo apt-get update --fix-missing` the playbooks ran correctly.

I modified the `bootstrap.sh` file and after `vagrant destroy -f && vagrant up` it ran like a charm! :)

**Comment by semberal** [comment]
Thank you for reporting this issue, I just pushed updating apt cache before installing dependencies.

**Comment by vodrazka** [comment]
good, thats a better solution :)
